# The URL the site will be built for
base_url = "https://ccarral.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

default_language = "es"

generate_feed = true

minify_html = true

title = "cosmic__cube"
description = "Cosas que solo me interesan a mi"

[languages.en]

[markdown]
highlight_code = true 
highlight_theme = "visual-studio-dark"

[slugify]
paths = "off"

[extra]
twitter = "@0xC4C4"
default_img = "images/tintan_y_yo.jpg"

[extra.analytics]
enabled=true
goatcounter_user = "cosmiccube"
