# The URL the site will be built for
base_url = "https://example.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

default_language = "es"

title = "Cosmic Cube"
description = "Cosas que solo me interesan a mi"

[extra]
twitter = "@0xC4C4"
default_img = "images/setup.jpg"

[extra.analytics]
enabled=true
goatcounter_user = "cosmiccube"
