# The URL the site will be built for
base_url = "https://example.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

default_language = "es"

title = "cosmic__cube"
description = "Cosas que solo me interesan a mi"


[languages.en.translations]

[extra]
twitter = "@0xC4C4"
default_img = "images/setup.jpg"
banner = "banner2.txt"

[extra.analytics]
enabled=true
goatcounter_user = "cosmiccube"

